[package]
name = "piscine-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
borrow = { version = "0.1.0", path = "borrow" }
division_and_remainder = { version = "0.1.0", path = "division_and_remainder" }
doubtful = { version = "0.1.0", path = "doubtful" }
fibonacci2 = { version = "0.1.0", path = "fibonacci2" }
find_factorial = { version = "0.1.0", path = "find_factorial" }
groceries = { version = "0.1.0", path = "groceries" }
matrix_transposition = { version = "0.1.0", path = "matrix_transposition" }
reverse_string = { version = "0.1.0", path = "reverse_string" }
scalar = { version = "0.1.0", path = "scalar" }
speed_transformation = { version = "0.1.0", path = "speed_transformation" }
string_literals = { version = "0.1.0", path = "string_literals" }
temperature_conv = { version = "0.1.0", path = "temperature_conv" }
to_url = { version = "0.1.0", path = "to_url" }
tuples_refs = { version = "0.1.0", path = "tuples_refs" }

[workspace]
members = [ "borrow", "division_and_remainder", "doubtful", "fibonacci2", "find_factorial", "groceries", "looping", "matrix_transposition", "reverse_string","scalar", "speed_transformation", "string_literals", "temperature_conv", "to_url", "tuples_refs"]
