[package]
name = "piscine-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
adding = { version = "0.1.0", path = "adding" }
adding_twice = { version = "0.1.0", path = "adding_twice" }
arrange_it = { version = "0.1.0", path = "arrange_it" }
arrays = { version = "0.1.0", path = "arrays" }
banner = { version = "0.1.0", path = "banner" }
bigger = { version = "0.1.0", path = "bigger" }
border_cross = { version = "0.1.0", path = "border_cross" }
borrow = { version = "0.1.0", path = "borrow" }
borrow_box = { version = "0.1.0", path = "borrow_box" }
borrow_me_the_reference = { version = "0.1.0", path = "borrow_me_the_reference" }
box_it = { version = "0.1.0", path = "box_it" }
box_recursion = { version = "0.1.0", path = "box_recursion" }
boxing_todo = { version = "0.1.0", path = "boxing_todo" }
capitalizing = { version = "0.1.0", path = "capitalizing" }
card_deck = { version = "0.1.0", path = "card_deck" }
changes = { version = "0.1.0", path = "changes" }
chrono = "0.4"
cipher = { version = "0.1.0", path = "cipher" }
circle = { version = "0.1.0", path = "circle" }
closures = { version = "0.1.0", path = "closures" }
collect = { version = "0.1.0", path = "collect" }
commits_stats = { version = "0.1.0", path = "commits_stats" }
copy = { version = "0.1.0", path = "copy" }
delete_prefix = { version = "0.1.0", path = "delete_prefix" }
diamond_creation = { version = "0.1.0", path = "diamond_creation" }
division_and_remainder = { version = "0.1.0", path = "division_and_remainder" }
does_it_fit = { version = "0.1.0", path = "does_it_fit" }
doubtful = { version = "0.1.0", path = "doubtful" }
drop_the_thread = { version = "0.1.0", path = "drop_the_thread" }
error_types = { version = "0.1.0", path = "error_types" }
events = { version = "0.1.0", path = "events" }
expected_variable = { version = "0.1.0", path = "expected_variable" }
fibonacci2 = { version = "0.1.0", path = "fibonacci2" }
find_factorial = { version = "0.1.0", path = "find_factorial" }
get_products = { version = "0.1.0", path = "get_products" }
groceries = { version = "0.1.0", path = "groceries" }
hashing = { version = "0.1.0", path = "hashing" }
highest = { version = "0.1.0", path = "highest" }
how_many_references = { version = "0.1.0", path = "how_many_references" }
iterators = { version = "0.1.0", path = "iterators" }
json = "0.12.4"
lalgebra_scalar = { version = "0.1.0", path = "lalgebra_scalar" }
lifetimes = { version = "0.1.0", path = "lifetimes" }
logic_number = { version = "0.1.0", path = "logic_number" }
macro_calculator = { version = "0.1.0", path = "macro_calculator" }
matrix = { version = "0.1.0", path = "matrix" }
matrix_mult = { version = "0.1.0", path = "matrix_mult" }
matrix_ops = { version = "0.1.0", path = "matrix_ops" }
matrix_transposition = { version = "0.1.0", path = "matrix_transposition" }
name_initials = { version = "0.1.0", path = "name_initials" }
ordinal = { version = "0.1.0", path = "ordinal" }
ownership = { version = "0.1.0", path = "ownership" }
pangram = { version = "0.1.0", path = "pangram" }
pig_latin = { version = "0.1.0", path = "pig_latin" }
ref_cell = { version = "0.1.0", path = "ref_cell" }
reverse_string = { version = "0.1.0", path = "reverse_string" }
rgb_match = { version = "0.1.0", path = "rgb_match" }
roman_numbers = { version = "0.1.0", path = "roman_numbers" }
roman_numbers_iter = { version = "0.1.0", path = "roman_numbers_iter" }
rot = { version = "0.1.0", path = "rot" }
sales = { version = "0.1.0", path = "sales" }
scalar = { version = "0.1.0", path = "scalar" }
scores = { version = "0.1.0", path = "scores" }
scytale_cipher = { version = "0.1.0", path = "scytale_cipher" }
searching = { version = "0.1.0", path = "searching" }
shopping_mall = { version = "0.1.0", path = "shopping_mall" }
simple_hash = { version = "0.1.0", path = "simple_hash" }
slices_to_map = { version = "0.1.0", path = "slices_to_map" }
speed_transformation = { version = "0.1.0", path = "speed_transformation" }
spelling = { version = "0.1.0", path = "spelling" }
stars = { version = "0.1.0", path = "stars" }
string_literals = { version = "0.1.0", path = "string_literals" }
string_permutation = { version = "0.1.0", path = "string_permutation" }
strings = { version = "0.1.0", path = "strings" }
talking = { version = "0.1.0", path = "talking" }
temperature_conv = { version = "0.1.0", path = "temperature_conv" }
tic_tac_toe = { version = "0.1.0", path = "tic_tac_toe" }
to_url = { version = "0.1.0", path = "to_url" }
traits = { version = "0.1.0", path = "traits" }
tuples_refs = { version = "0.1.0", path = "tuples_refs" }
vector_operations = { version = "0.1.0", path = "vector_operations" }

[workspace]
members = [ "adding", "adding_twice", "arrange_it", "arrays", "banner", "bigger", "blood_types", "border_cross", "borrow", "borrow_box", "borrow_me_the_reference", "box_it", "box_recursion", "boxing_todo", "capitalizing", "card_deck", "changes", "cipher", "circle", "closures", "collect", "commits_stats", "copy", "delete_prefix", "diamond_creation", "division_and_remainder", "does_it_fit", "doubtful", "drop_the_thread", "easy_traits", "edit_distance", "error_types", "events", "expected_variable", "fibonacci2", "find_factorial", "generics", "generics_list", "get_products", "groceries", "handling", "hashing", "highest", "how_many_references", "iterators", "lalgebra_scalar", "lalgebra_vector", "lib", "lifetimes", "logic_number", "looping", "macro_calculator", "matrix", "matrix_mult", "matrix_ops", "matrix_transposition", "middle_day", "mobs", "name_initials", "ordinal", "ownership", "pangram", "panic", "pig_latin", "profanity_filter", "question_mark", "ref_cell", "reverse_string", "rgb_match", "roman_numbers", "roman_numbers_iter", "rot", "sales","scalar", "scores", "scytale_cipher", "searching", "shopping_mall", "simple_hash", "slices_to_map", "speed_transformation", "spelling", "stars", "string_literals", "string_permutation", "strings", "talking", "temperature_conv", "tic_tac_toe", "to_url", "traits", "tuples_refs", "unwrap_or_expect", "vector_operations"]
