[package]
name = "piscine-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
fibonacci2 = { version = "0.1.0", path = "fibonacci2" }
find_factorial = { version = "0.1.0", path = "find_factorial" }
groceries = { version = "0.1.0", path = "groceries" }
matrix_transposition = { version = "0.1.0", path = "matrix_transposition" }
reverse_string = { version = "0.1.0", path = "reverse_string" }
scalar = { version = "0.1.0", path = "scalar" }
speed_transformation = { version = "0.1.0", path = "speed_transformation" }
temperature_conv = { version = "0.1.0", path = "temperature_conv" }

[workspace]
members = [ "fibonacci2", "find_factorial", "groceries", "looping", "matrix_transposition", "reverse_string","scalar", "speed_transformation", "temperature_conv"]
