[package]
name = "piscine-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
arrange_it = { version = "0.1.0", path = "arrange_it" }
borrow = { version = "0.1.0", path = "borrow" }
borrow_me_the_reference = { version = "0.1.0", path = "borrow_me_the_reference" }
changes = { version = "0.1.0", path = "changes" }
circle = { version = "0.1.0", path = "circle" }
copy = { version = "0.1.0", path = "copy" }
division_and_remainder = { version = "0.1.0", path = "division_and_remainder" }
doubtful = { version = "0.1.0", path = "doubtful" }
fibonacci2 = { version = "0.1.0", path = "fibonacci2" }
find_factorial = { version = "0.1.0", path = "find_factorial" }
groceries = { version = "0.1.0", path = "groceries" }
matrix_transposition = { version = "0.1.0", path = "matrix_transposition" }
name_initials = { version = "0.1.0", path = "name_initials" }
ownership = { version = "0.1.0", path = "ownership" }
reverse_string = { version = "0.1.0", path = "reverse_string" }
scalar = { version = "0.1.0", path = "scalar" }
speed_transformation = { version = "0.1.0", path = "speed_transformation" }
string_literals = { version = "0.1.0", path = "string_literals" }
temperature_conv = { version = "0.1.0", path = "temperature_conv" }
tic_tac_toe = { version = "0.1.0", path = "tic_tac_toe" }
to_url = { version = "0.1.0", path = "to_url" }
tuples_refs = { version = "0.1.0", path = "tuples_refs" }

[workspace]
members = [ "arrange_it", "borrow", "borrow_me_the_reference", "changes", "circle", "copy", "division_and_remainder", "doubtful", "fibonacci2", "find_factorial", "groceries", "looping", "matrix_transposition", "name_initials", "ownership", "reverse_string","scalar", "speed_transformation", "string_literals", "temperature_conv", "tic_tac_toe", "to_url", "tuples_refs"]
